theme: jekyll-theme-slate
title: Credit Qualification
description: This tool was designed to provide crucial information in determining which clients can access a bank loan and which clients should not. Real world data was provided for the making of this tool, so a data privacy disclaimer was needed.
